name: Build & Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.101

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Bundle artifacts
        run: |
            cd ./HearthDb/bin/Release/netstandard2.0
            zip HearthDb.zip HearthDb.dll HearthDb.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HearthDb.zip
          path: "./HearthDb/bin/Release/netstandard2.0/HearthDb.zip"

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'
    permissions:
     id-token: write
     contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: HearthDb.zip
          path: bin

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.HDT_LIBS_AWS_DEPLOY_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy
        run: aws s3 cp bin/*.zip s3://libs.hearthsim.net/hdt/
